home/urls.py
from django.urls import path
from . import views
from .views import MatkulView, MatkulDetail, MatkulDelete

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('projects', views.projects, name='projects'),
    path('matakuliah', MatkulView.as_view(), name='matakuliah'),
    path('detail/<int:pk>/', MatkulDetail.as_view(), name='matkul-detail'),
    path('matakuliah-add', views.matkul_add, name='matakuliah-add'),
    path('detail/<int:pk>/remove', MatkulDelete.as_view(), name='matkul-delete'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path("story6/", include("story6.urls")),
    path("story7/", include("story7.urls")),
    path("story8/", include("story8.urls")),
    path('story9/', include("story9.urls")),
    path('story9/', include('django.contrib.auth.urls'))
]

story6/urls.py
from django.urls import path
from . import views
from .views import KegiatanView, AddKegiatanView, AddMemberView

app_name = 'story6'

urlpatterns = [
    path('kegiatan', KegiatanView.as_view(), name='kegiatan'),
    path('add-kegiatan', AddKegiatanView.as_view(), name='add-kegiatan'),
    path('add-member', AddMemberView.as_view(), name='add-member')
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('experiences', views.experiences, name='experiences')
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
    path('data/', views.search, name='search'),
]

story9/urls.py
from django.urls import path, include
from .views import UserRegisterView

app_name = 'story9'

urlpatterns = [
    path('register/',UserRegisterView.as_view(), name="register")
]

home/models.py
from django.db import models

class Matkul(models.Model):
    matakuliah = models.CharField(max_length=300)
    dosen = models.CharField(max_length=300)
    sks = models.CharField(max_length=300)
    deskripsi = models.TextField()
    semester = models.CharField(max_length=300)
    kelas = models.CharField(max_length=300)

    def __str__(self):
        return self.matakuliah
# Create your models here.

story6/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Kegiatan(models.Model):
    activity = models.CharField(max_length=300)

    def __str__(self):
        return self.activity

    def get_absolute_url(self):
        return reverse("story6:kegiatan")
    

class Attendee(models.Model):
    attendee = models.CharField(max_length=300)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return self.attendee

    def get_absolute_url(self):
        return reverse("story6:kegiatan")

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = [
            'matakuliah',
            'dosen',
            'sks',
            'deskripsi',
            'semester',
            'kelas'
        ]
        widgets = {
            'matakuliah':forms.TextInput(attrs={'class':'form-control'}),
            'dosen':forms.TextInput(attrs={'class':'form-control'}),
            'sks':forms.TextInput(attrs={'class':'form-control'}),
            'deskripsi':forms.Textarea(attrs={'class':'form-control'}),
            'semester':forms.TextInput(attrs={'class':'form-control'}),
            'kelas':forms.TextInput(attrs={'class':'form-control'})
        }

home/views.py
from django.shortcuts import render
from .forms import MatkulForm
from .models import Matkul
from django.views.generic import ListView, DetailView, DeleteView
from django.urls import reverse_lazy
# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def about(request):
    return render(request, 'home/about.html')

def projects(request):
    return render(request, 'home/projects.html')

def matkul_add(request):
    form = MatkulForm(request.POST or None)
    if form.is_valid():
        form.save()

    context = {
        "form":form
    }
    return render(request, 'home/matakuliah-add.html', context)

class MatkulView(ListView):
    model = Matkul
    template_name = "home/matakuliah.html"

class MatkulDetail(DetailView):
    model = Matkul
    template_name = "home/matakuliah-details.html"

class MatkulDelete(DeleteView):
    model = Matkul
    template_name = "home/matakuliah-delete.html"
    success_url = reverse_lazy('home:matakuliah')

story6/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, DeleteView, CreateView
from .models import Kegiatan, Attendee


# Create your views here.
class KegiatanView(ListView):
    context_object_name = 'kegiatan_list'    
    template_name = 'story6/kegiatan.html'
    queryset = Kegiatan.objects.all()

    def get_context_data(self, **kwargs):
        context = super(KegiatanView, self).get_context_data(**kwargs)
        context['attendees'] = Attendee.objects.all()
        return context

class AddKegiatanView(CreateView):
    model = Kegiatan
    template_name = 'story6/kegiatan-add.html'
    fields = '__all__'

class AddMemberView(CreateView):
    model = Attendee
    template_name = 'story6/member-add.html'
    fields = '__all__'              

story7/views.py
from django.shortcuts import render

# Create your views here.
def experiences(request):
    return render(request, 'story7/experiences.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
    return render(request, 'story8/search.html')

def search(request):
    searchterm = request.GET['q']
    url_dest = 'https://www.googleapis.com/books/v1/volumes?q=' + searchterm
    result = requests.get(url_dest)
    data = json.loads(result.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class UserRegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

home/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <title>Andrew Nehemia H</title>
    <link rel="icon" href="../static/img/logo.svg">
  </head>
  <body style="background-color: #222;">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-black rounded">
            <a class="navbar-brand" href="/">
                <img src="../../static/img/logo.svg" width="40" height="40" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
              <div class="mr-auto"></div>
              <div class="navbar-nav">
                <a class="nav-link mr-3 text-white" href="{% url 'home:about' %}">About</a>
                <a class="nav-link mr-3 text-white" href="{% url 'home:projects' %}">Projects</a>
                <li class="nav-item dropdown mr-3 my-0 ml-0">
                  <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Kegiatan
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:black;">
                    <a class="nav-link text-white" href="{% url 'story6:kegiatan' %}">List Kegiatan</a>
                    <a class="nav-link text-white" href="{% url 'story6:add-kegiatan' %}">Tambah Kegiatan</a>
                    <a class="nav-link text-white" href="{% url 'story6:add-member' %}">Tambah Member</a>
                  </div>
                </li>
                <a class="nav-link mr-3 text-white" href="{% url 'home:matakuliah' %}">Mata Kuliah</a>
                <a class="nav-link mr-3 text-white" href="{% url 'home:matakuliah-add' %}">Tambah Mata Kuliah</a>
                <a class="nav-link mr-3 text-white" href="{% url 'story7:experiences' %}">Experiences</a>
                <a class="nav-link mr-3 text-white" href="{% url 'story8:index' %}">Search Books</a>
                <a class="nav-link mr-3 text-white" href="{% url 'story9:register' %}">Register</a>
                <a class="nav-link mr-3 text-white" href="{% url 'login' %}">Login</a>
                <a class="nav-link mr-3 text-white" href="{% url 'logout' %}">Logout</a>
              </div>
            </div>
          </nav>
    </header>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/matakuliah-add.html
{% extends 'base.html' %}

    {% block content %}
    <main>
        <img src="../../static/img/matkuladd.svg" class="mx-auto d-block mb-5 img-fluid" alt="matkuladd">
        <div class="container big-wrapper text-light">
            <div class="form-group">
                <form method="POST"> {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value='Save' class="btn btn-outline-light btn-lg text-light btn-block matkuladd-button">
                </form>
            </div>
        </div>
    </main>
    {% endblock %}

home/templates/home/matakuliah.html
{% extends 'base.html' %}

{% block content %}
<main>
    <img src="../../static/img/matakuliah.svg" class="mx-auto d-block mb-5 img-fluid" alt="matkul">
    <div class="container text-xl-center text-lg-center text-md-center text-sm-center big-wrapper text-light">
        <div class="row d-flex justify-content-center">
        {% for matkul in object_list %}
        <div class="card m-2" style="width: 18rem">
            <div class="card-body d-flex flex-column">
                <h5 class="card-title">
                    {{ matkul.matakuliah }}
                </h5>
                <p class="card-text text-dark">
                    {{ matkul.deskripsi }}
                </p>
                <p class="card-text text-dark">
                    {{ matkul.kelas }}
                </p>
                <div class="mt-auto">
                <a href="{% url 'home:matkul-detail' matkul.pk %}"
                    class="btn btn-outline-light btn-lg text-light btn-block matkul-buttons">Details</a>
                <a href="{% url 'home:matkul-delete' matkul.pk %}"
                    class="btn btn-outline-light btn-lg text-light btn-block matkul-buttons">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

home/templates/home/projects.html
{% extends 'base.html' %}

  {% block content %}
    <main>
      <img src="../../static/img/projects.svg" class="mx-auto d-block mb-5"  alt="projects-title">
      <div class="container text-xl-left text-lg-left text-md-center text-sm-center big-wrapper">
      <img src="../../static/img/budayakb.png" alt="">
      </div>
    </main>
    
{% endblock %}

story6/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <title>Andrew Nehemia H</title>
    <link rel="icon" href="../static/img/logo.svg">
  </head>
  <body style="background-color: #222;">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-black rounded">
            <a class="navbar-brand" href="/">
                <img src="../../static/img/logo.svg" width="40" height="40" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
              <div class="mr-auto"></div>
              <div class="navbar-nav">
                <a class="nav-link mr-3 text-white" href="{% url 'home:about' %}">About</a>
                <a class="nav-link mr-3 text-white" href="{% url 'home:projects' %}">Projects</a>
                <li class="nav-item dropdown mr-3 my-0 ml-0">
                  <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Kegiatan
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:black;">
                    <a class="nav-link text-white" href="{% url 'story6:kegiatan' %}">List Kegiatan</a>
                    <a class="nav-link text-white" href="{% url 'story6:add-kegiatan' %}">Tambah Kegiatan</a>
                    <a class="nav-link text-white" href="{% url 'story6:add-member' %}">Tambah Member</a>
                  </div>
                </li>
                <a class="nav-link mr-3 text-white" href="{% url 'home:matakuliah' %}">Mata Kuliah</a>
                <a class="nav-link mr-3 text-white" href="{% url 'home:matakuliah-add' %}">Tambah Mata Kuliah</a>
                <a class="nav-link mr-3 text-white" href="{% url 'story7:experiences' %}">Experiences</a>
                <a class="nav-link mr-3 text-white" href="{% url 'story8:index' %}">Search Books</a>
              </div>
            </div>
          </nav>
    </header>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

story7/templates/story7/experiences.html
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Accordion</title>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<style>
        @import url('https://fonts.googleapis.com/css?family=Muli:400,700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap');

        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Muli', sans-serif;
          }
          
          .judul {
            font-family: 'Fredoka One', cursive;
            text-align: center;
            color: orange;
            margin-top: 5%;
            font-size: 500%;
          }
          
          .unordered{
            padding: 15px;
            font-size: 15px;
            line-height: 22px;
            color: #fff;
            list-style: none;   
          }
          
          body{
            background: rgb(41, 41, 41);
          }
          
          .wrapper{
            width: 500px;
            margin: 80px auto 0;
          }
          
          .wrapper .accordion_wrap .accordion_header{
            width: 100%;
            height: 50px;
            background: rgb(255, 255, 255);
            padding: 15px;
            color:orange;
            font-weight: 700;
            border-bottom: 2px solidorange;
            position: relative;
            cursor: pointer;
          }
          
          .wrapper .accordion_wrap:first-child .accordion_header{
            border-top-left-radius: 3px;
            border-top-right-radius: 3px;
          }
          
          .wrapper .accordion_wrap:last-child .accordion_header{
            border-bottom: 2px solid transparent;
            border-bottom-left-radius: 3px;
            border-bottom-right-radius: 3px;
          }
          
          .wrapper .accordion_wrap:last-child .accordion_header:hover{
            border-bottom: 2px solid transparent;
          }
          
          .wrapper .accordion_wrap .accordion_header:hover{
            color: black;
            border-color: black;
          }
          
          .wrapper .accordion_wrap .accordion_header:hover:before,
          .wrapper .accordion_wrap .accordion_header:hover:after{
            background: black;
          }
          
          .wrapper .accordion_wrap .accordion_body{
            width: 100%;
            height: 0px;
            transition: all 0.5s ease;
            background:orange;
            overflow: hidden;
          }
          
          .wrapper .accordion_wrap .accordion_body p{
            padding: 15px;
            font-size: 15px;
            line-height: 22px;
            color: #fff;
          }
          
          .wrapper .accordion_wrap .accordion_header.active{
            color: black; 
            border-color: black;
          }
          
          .wrapper .accordion_wrap:last-child .accordion_header.active{
            border-bottom: 2px solid black;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
          }
          
          .wrapper .accordion_wrap .accordion_header.active + .accordion_body{
            height: 180px;
          }
          
          .RightFloat {
            float: right;
            display: flex;
          }
          
          .directional-buttons{
            display:inline-block;
            padding:0.35em 1.2em;
            border:0.1em solid #FFFFFF;
            margin:0 0.3em 0.3em 0;
            border-radius:0.12em;
            box-sizing: border-box;
            text-decoration:none;
            font-family:'Roboto',sans-serif;
            font-weight:700;
            color:black;
            text-align:center;
            transition: all 0.2s;
            }
          
            .directional-buttons:hover{
            color: #FFFFFF;
            background-color:orange;
            }
          
          .directional-buttons-rev {
            padding:0.35em 1.2em;
            border:0.1em solid #ffffff78;
            margin:0 0.3em 0.3em 0;
            border-radius:0.12em;
            box-sizing: border-box;
            text-decoration:none;
            font-family:'Roboto',sans-serif;
            font-weight:700;
            color:black;
            text-align:center;
            transition: all 0.2s;
            background-color: #FFFFFF;
            margin-left: 46%;
          }
            
          .directional-buttons-rev:hover {
            color: #ffffff;
            background-color:orange;
            
          }
    </style>
</head>

<body>
<h1 class="judul">EXPERIENCES</h1>
<div class="wrapper">
  <div class="accordion_wrap accordion_1">
    <div class="accordion_header">
      Identity
      <div class="RightFloat">
        <button value='up' class="directional-buttons">Up</button>
        <button value='down' class="directional-buttons">Down</button>
      </div>
    </div>
    <div class="accordion_body">
      <p>Andrew Nehemia Hutapea, 19.</p>
    </div>
    
  </div>
  <div class="accordion_wrap accordion_2">
    <div class="accordion_header">
      Current Activity
      <div class="RightFloat">
        <button value='up' class="directional-buttons">Up</button>
        <button value='down' class="directional-buttons">Down</button>
      </div>
    </div>
    <div class="accordion_body">
       <p>Currently studying from home in Universitas Indonesia.</p>
    </div>
    
  </div>
  <div class="accordion_wrap accordion_3">
    <div class="accordion_header">
      Organizational Experience
      <div class="RightFloat">
        <button value='up' class="directional-buttons">Up</button>
        <button value='down' class="directional-buttons">Down</button>
      </div>
    </div>
    <div class="accordion_body">
      <p></p>
    </div>
    
  </div>
  <div class="accordion_wrap accordion_4">
    <div class="accordion_header">
      Achievements
      <div class="RightFloat">
        <button value='up' class="directional-buttons">Up</button>
        <button value='down' class="directional-buttons">Down</button>
      </div>
    </div>
    <div class="accordion_body">
      <ul class="unordered">
        <li>
          Got in UI
        </li>
        <li>
          Platinum in Apex
        </li>
        <li>
          Top 1k Shiho
        </li>
        <li>
          Octane main
        </li>
      </ul>
    </div>
    
  </div>
</div>
<br><br>
<a href="{% url 'home:index' %}" class="directional-buttons-rev">Back to Main Page</a>


<script>
  $(document).ready(function(){
    $(".accordion_header").click(function(){
      if ($(this).hasClass("active")) {
        $(this).removeClass("active");
      } else {
        $(this).addClass("active"); 
      }
            
    });
  });

  function moveUp(item) {
    var prev = item.prev();
    if (prev.length == 0)
        return;
    prev.css('z-index', 999).css('position','relative').animate({ top: item.height() }, 250);
    item.css('z-index', 1000).css('position', 'relative').animate({ top: '-' + prev.height() }, 300, function () {
        prev.css('z-index', '').css('top', '').css('position', '');
        item.css('z-index', '').css('top', '').css('position', '');
        item.insertBefore(prev);
    });
}
function moveDown(item) {
    var next = item.next();
    if (next.length == 0)
        return;
    next.css('z-index', 999).css('position', 'relative').animate({ top: '-' + item.height() }, 250);
    item.css('z-index', 1000).css('position', 'relative').animate({ top: next.height() }, 300, function () {
        next.css('z-index', '').css('top', '').css('position', '');
        item.css('z-index', '').css('top', '').css('position', '');
        item.insertAfter(next);
    });
}

$('button').click(function() { 
    var btn = $(this);
    var val = btn.val();
    if (val == 'up')
        moveUp(btn.parents('.accordion_wrap'));
    else
        moveDown(btn.parents('.accordion_wrap'));
    
    $(".accordion_header").removeClass("active");
});
  
  
</script>
</body>
</html>

story9/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <title>Andrew Nehemia H</title>
    <link rel="icon" href="../static/img/logo.svg">
  </head>
  <body style="background-color: #222;">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-black rounded">
            <a class="navbar-brand" href="/">
                <img src="../../static/img/logo.svg" width="40" height="40" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
              <div class="mr-auto"></div>
              <div class="navbar-nav">
                <a class="nav-link mr-3 text-white" href="{% url 'home:about' %}">About</a>
                <a class="nav-link mr-3 text-white" href="{% url 'home:projects' %}">Projects</a>
                <li class="nav-item dropdown mr-3 my-0 ml-0">
                  <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Kegiatan
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:black;">
                    <a class="nav-link text-white" href="{% url 'story6:kegiatan' %}">List Kegiatan</a>
                    <a class="nav-link text-white" href="{% url 'story6:add-kegiatan' %}">Tambah Kegiatan</a>
                    <a class="nav-link text-white" href="{% url 'story6:add-member' %}">Tambah Member</a>
                  </div>
                </li>
                <a class="nav-link mr-3 text-white" href="{% url 'home:matakuliah' %}">Mata Kuliah</a>
                <a class="nav-link mr-3 text-white" href="{% url 'home:matakuliah-add' %}">Tambah Mata Kuliah</a>
                <a class="nav-link mr-3 text-white" href="{% url 'story7:experiences' %}">Experiences</a>
                <a class="nav-link mr-3 text-white" href="{% url 'story8:index' %}">Search Books</a>
                <a class="nav-link mr-3 text-white" href="{% url 'story9:register' %}">Register</a>
                <a class="nav-link mr-3 text-white" href="{% url 'login' %}">Login</a>
              </div>
            </div>
          </nav>
    </header>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>